<?php

namespace AppBundle\Repository;

/**
 * DeletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeletionRepository extends \Doctrine\ORM\EntityRepository
{
}
